version: 1
build:
  # Unable to run tests because of no Docker agent available in OCD3 yet. https://mekomsolutions.atlassian.net/browse/INFRA-318
  bash_commands: "mvn clean install -DskipTests"
deploy:
  # Do not deploy via OCD3. Publishing is done via GitHub Actions.
  bash_commands: "exit 0"
