name: Build and Publish

on:
  push:
    tags:
      - '*'
    branches:
      - master
      - '[0-9]+.[0-9]+.x'
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Build
        run: mvn --batch-mode clean package

  publish:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref,'refs/heads') || startsWith(github.ref,'refs/tags') }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Set settings.xml
        if: ${{ ( github.repository == 'mekomsolutions/openmrs-dbsync') && (github.event_name != 'pull_request') }}
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: |
            [{
              "id": "mks-nexus-releases",
              "username": "${{ secrets.NEXUS_USERNAME }}",
              "password": "${{ secrets.NEXUS_PASSWORD }}"
            },
            {
              "id": "mks-nexus-snapshots",
              "username": "${{ secrets.NEXUS_USERNAME }}",
              "password": "${{ secrets.NEXUS_PASSWORD }}"
            }]
            
      - name: Build
        run: mvn --batch-mode clean deploy
